//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nom1Done.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class NMQR_RefIdentification
    {
        [Key]
        public long RefIdenID { get; set; }
        public long SublineItemID { get; set; }
        public string ReferenceIdentificationQualifier { get; set; }
        public string ServiceProviderActivityCode { get; set; }
    }
}
