//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nom1Done.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class NMQR_ReferenceIdentification_N9
    {
        [Key]
        public long RefIdenN9ID { get; set; }
        public long NMQRID { get; set; }
        public string ReferenceIdentificationQualifier { get; set; }
        public string ReferenceIdentification { get; set; }
        public string DateTimeQualifier { get; set; }
        public string DateTimePeriodFormatQualifier { get; set; }
        public string BeginningDate { get; set; }
        public string BeginningTime { get; set; }
        public string EndingDate { get; set; }
        public string EndingTime { get; set; }
        public string ServiceRequesterContract { get; set; }
    }
}
