//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nom1Done.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class NMQR_Header
    {
        [Key]
        public long NMQRID { get; set; }
        public System.Guid TransactionID { get; set; }
        public string TransactionSetIdentifierCode { get; set; }
        public string TransactionSetControlNumber { get; set; }
        public string TransactionSetPurposeCode { get; set; }
        public string ReferenceIdentification { get; set; }
        public string NominationIssueDate { get; set; }
        public string TransactionTypeCode { get; set; }
        public string ExceptionOccured { get; set; }
        public string Reject_HeaderLevelError { get; set; }
        public string Accept { get; set; }
    }
}
