//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nom1Done.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class NMQR_Information
    {
        [Key]
        public long InfoID { get; set; }
        public long SegmentID { get; set; }
        public string CodeQualifierCode { get; set; }
        public string ValidationCode { get; set; }
        public string ValidationMessage { get; set; }
    }
}
