//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nom1Done.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class RURD_Name_Head
    {
        [Key]
        public long Name_HeadID { get; set; }
        public System.Guid TransactionID { get; set; }
        public string EntityIdentifier { get; set; }
        public string IdentifierCodeQualifier { get; set; }
        public string TransportationServiceProvider { get; set; }
        public string TransportationServiceProviderPropCode { get; set; }
        public string RequesterCompCode { get; set; }
        public string RequesterCompCodePropCode { get; set; }
    }
}
