// <auto-generated />
namespace Nom1Done.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_TransactionTypeInLocation_PackageIdInV4Nomination : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_TransactionTypeInLocation_PackageIdInV4Nomination));
        
        string IMigrationMetadata.Id
        {
            get { return "201801011137485_add_TransactionTypeInLocation_PackageIdInV4Nomination"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
