// <auto-generated />
namespace Nom1Done.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fuelpercentcolumninNoms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fuelpercentcolumninNoms));
        
        string IMigrationMetadata.Id
        {
            get { return "201711131321369_fuelpercentcolumninNoms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
