//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nom1Done.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class NMQR_NameHead
    {
        [Key]
        public long NameheadID { get; set; }
        public long NMQRID { get; set; }
        public string EntityIdentifierCode { get; set; }
        public string IdentificationCodeQualifier { get; set; }
        public string ServiceRequester { get; set; }
        public string ServiceRequesterProprietaryCode { get; set; }
        public string TransportationServiceProvider { get; set; }
        public string TranportationServiceProviderProprietaryCode { get; set; }
    }
}
