//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nom1Done.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class UPRD_DateTimeRef
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public System.Guid DateTimeRefID { get; set; }
        public System.Guid TransactionID { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.TimeSpan> BeginTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
