//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nom1Done.Model
{
    using System;
    using System.Collections.Generic;
    
    public class UPRD
    {
        public int Id { get; set; }
        public System.Guid TransactionID { get; set; }
        public string TransactionSetControlNumbar { get; set; }
        public string RequestID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsSend { get; set; }
    }
}
