//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nom1Done.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class UPRD_NameHead
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public System.Guid NameHeadID { get; set; }
        public System.Guid TransactionID { get; set; }
        public string TransportationServiceProvider { get; set; }
        public string TransportationServiceProviderPropCode { get; set; }
        public string RequesterCompanyCode { get; set; }
        public string RequesterCompanyCodePropCode { get; set; }
    }
}
