//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralisedUprd.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outbox
    {
        public int ID { get; set; }
        public System.Guid MessageID { get; set; }
        public int DatasetID { get; set; }
        public int StatusID { get; set; }
        public string GISB { get; set; }
        public bool IsTest { get; set; }
        public int PipelineID { get; set; }
        public int CompanyID { get; set; }
        public bool IsScheduled { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
