//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralisedUprd.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingPartnerWorksheet
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int PipelineID { get; set; }
        public string UsernameLive { get; set; }
        public string PasswordLive { get; set; }
        public string URLLive { get; set; }
        public string KeyLive { get; set; }
        public string UsernameTest { get; set; }
        public string PasswordTest { get; set; }
        public string URLTest { get; set; }
        public string KeyTest { get; set; }
        public string ReceiveSubSeperator { get; set; }
        public string ReceiveDataSeperator { get; set; }
        public string ReceiveSegmentSeperator { get; set; }
        public string SendSubSeperator { get; set; }
        public string SendDataSeperator { get; set; }
        public string SendSegmentSeperator { get; set; }
        public bool IsTest { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string PipeDuns { get; set; }
    }
}
