//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralisedUprd.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public long Id { get; set; }
        public string TransactionId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
