//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralisedUprd.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WatchlistRule
    {
        public int Id { get; set; }
        public int ColumnId { get; set; }
        public int OperatorId { get; set; }
        public string RuleValue { get; set; }
        public int WatchlistId { get; set; }
        public string PipelineDuns { get; set; }
        public string LocationIdentifier { get; set; }
        public bool AlertSent { get; set; }
        public int AlertFrequency { get; set; }
        public bool IsCriticalNotice { get; set; }
        public string UpperRuleValue { get; set; }
    
        public virtual Watchlist Watchlist { get; set; }
    }
}
