//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralisedUprd.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileSysIncomingData
    {
        public long Id { get; set; }
        public string MessageId { get; set; }
        public string DataReceived { get; set; }
        public System.DateTime ReceivedAt { get; set; }
        public bool IsProcessed { get; set; }
        public string DecryptedData { get; set; }
        public string PipeDuns { get; set; }
        public string DatasetType { get; set; }
    }
}
