//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralisedUprd.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class metadataDataset
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Identifier { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public string Direction { get; set; }
        public bool IsUPRDAttribute { get; set; }
        public bool IsActive { get; set; }
    }
}
