//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralisedUprd.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OACYPerTransaction
    {
        public long OACYID { get; set; }
        public System.Guid TransactionID { get; set; }
        public System.Guid ReceiceFileID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string TransactionServiceProviderPropCode { get; set; }
        public string TransactionServiceProvider { get; set; }
        public Nullable<System.DateTime> PostingDateTime { get; set; }
        public Nullable<System.DateTime> EffectiveGasDayTime { get; set; }
        public string Loc { get; set; }
        public string LocName { get; set; }
        public string LocZn { get; set; }
        public string FlowIndicator { get; set; }
        public string LocPropDesc { get; set; }
        public string LocQTIDesc { get; set; }
        public string MeasurementBasis { get; set; }
        public string ITIndicator { get; set; }
        public string AllQtyAvailableIndicator { get; set; }
        public long DesignCapacity { get; set; }
        public long OperatingCapacity { get; set; }
        public long TotalScheduleQty { get; set; }
        public long OperationallyAvailableQty { get; set; }
        public Nullable<int> PipelineID { get; set; }
        public string CycleIndicator { get; set; }
        public decimal AvailablePercentage { get; set; }
    }
}
