//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralisedUprd.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwntPerTransaction
    {
        public long Id { get; set; }
        public System.Guid TransactionId { get; set; }
        public System.Guid ReceiveFileId { get; set; }
        public int PipelineId { get; set; }
        public string TransactionIdentifierCode { get; set; }
        public string TransactionControlNumber { get; set; }
        public string TransactionSetPurposeCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> NoticeEffectiveDateTime { get; set; }
        public Nullable<System.DateTime> NoticeEndDateTime { get; set; }
        public Nullable<System.DateTime> PostingDateTime { get; set; }
        public Nullable<System.DateTime> ResponseDateTime { get; set; }
        public string TransportationserviceProvider { get; set; }
        public string TransportationServiceProviderPropCode { get; set; }
        public string CriticalNoticeIndicator { get; set; }
        public string FreeFormMessageText { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Message { get; set; }
        public string NoticeId { get; set; }
        public string NoticeTypeDesc1 { get; set; }
        public string NoticeTypeDesc2 { get; set; }
        public string ReqrdResp { get; set; }
        public string Subject { get; set; }
        public string PriorNotice { get; set; }
        public string NoticeStatusDesc { get; set; }
    }
}
