//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralisedUprd.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnscPerTransaction
    {
        public long UnscID { get; set; }
        public System.Guid TransactionID { get; set; }
        public System.Guid ReceiveFileID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int PipelineID { get; set; }
        public string TransactionServiceProvider { get; set; }
        public string TransactionServiceProviderPropCode { get; set; }
        public string Loc { get; set; }
        public string LocName { get; set; }
        public string LocZn { get; set; }
        public string LocPurpDesc { get; set; }
        public string LocQTIDesc { get; set; }
        public string MeasBasisDesc { get; set; }
        public long TotalDesignCapacity { get; set; }
        public long UnsubscribeCapacity { get; set; }
        public Nullable<System.DateTime> PostingDateTime { get; set; }
        public Nullable<System.DateTime> EffectiveGasDayTime { get; set; }
        public Nullable<System.DateTime> EndingEffectiveDay { get; set; }
        public decimal ChangePercentage { get; set; }
    }
}
