//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralisedUprd.Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UprdDbEntities1 : DbContext
    {
        public UprdDbEntities1()
            : base("name=UprdDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ApplicationLog> ApplicationLogs { get; set; }
        public virtual DbSet<EmailQueue> EmailQueues { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<GISBInbox> GISBInboxes { get; set; }
        public virtual DbSet<GISBOutbox> GISBOutboxes { get; set; }
        public virtual DbSet<Inbox> Inboxes { get; set; }
        public virtual DbSet<IncomingData> IncomingDatas { get; set; }
        public virtual DbSet<JobStackErrorLog> JobStackErrorLogs { get; set; }
        public virtual DbSet<JobWorkflow> JobWorkflows { get; set; }
        public virtual DbSet<metadataDataset> metadataDatasets { get; set; }
        public virtual DbSet<metadataErrorCode> metadataErrorCodes { get; set; }
        public virtual DbSet<metadataPipelineEncKeyInfo> metadataPipelineEncKeyInfoes { get; set; }
        public virtual DbSet<OACYPerTransaction> OACYPerTransactions { get; set; }
        public virtual DbSet<Outbox_MultipartForm> Outbox_MultipartForm { get; set; }
        public virtual DbSet<Outbox> Outboxes { get; set; }
        public virtual DbSet<PipelineEDISetting> PipelineEDISettings { get; set; }
        public virtual DbSet<Pipeline> Pipelines { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<ShipperCompany> ShipperCompanies { get; set; }
        public virtual DbSet<Shipper> Shippers { get; set; }
        public virtual DbSet<SwntPerTransaction> SwntPerTransactions { get; set; }
        public virtual DbSet<TaskMgrJob> TaskMgrJobs { get; set; }
        public virtual DbSet<TaskMgrXml> TaskMgrXmls { get; set; }
        public virtual DbSet<TradingPartnerWorksheet> TradingPartnerWorksheets { get; set; }
        public virtual DbSet<TransactionLog> TransactionLogs { get; set; }
        public virtual DbSet<TransportationServiceProvider> TransportationServiceProviders { get; set; }
        public virtual DbSet<UnscPerTransaction> UnscPerTransactions { get; set; }
        public virtual DbSet<UPRDStatu> UPRDStatus { get; set; }
        public virtual DbSet<WatchListMailAlertUPRDMapping> WatchListMailAlertUPRDMappings { get; set; }
        public virtual DbSet<DataTypeGrouping> DataTypeGroupings { get; set; }
        public virtual DbSet<LogicalOperator> LogicalOperators { get; set; }
        public virtual DbSet<MasterColumn> MasterColumns { get; set; }
        public virtual DbSet<FileSysIncomingData> FileSysIncomingDatas { get; set; }
        public virtual DbSet<WatchListPipelineMapping> WatchListPipelineMappings { get; set; }
        public virtual DbSet<CounterParty> CounterParties { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<WatchlistRule> WatchlistRules { get; set; }
        public virtual DbSet<Watchlist> Watchlists { get; set; }
        public virtual DbSet<SQTSReductionReason> SQTSReductionReasons { get; set; }
    }
}
