//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralisedUprd.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WatchListMailAlertUPRDMapping
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int WatchListId { get; set; }
        public int DataSetId { get; set; }
        public long UprdID { get; set; }
        public Nullable<System.DateTime> EmailSentDateTime { get; set; }
    }
}
