//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nom1Done.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class RURD_LINDetail_RefrenceNumber
    {
        [Key]
        public long ReferenceNumberID { get; set; }
        public long LineSegmentID { get; set; }
        public string ReferenceNumberQualifier { get; set; }
        public string DataAvailabilityCode { get; set; }
    }
}
