//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nom1Done.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class RURD_LINDetailSegment
    {
        [Key]
        public long LINSegmentID { get; set; }
        public System.Guid TransactionID { get; set; }
        public string AssignedIdentification { get; set; }
        public string ProductServiceID_02 { get; set; }
        public string DatasetsRequested_03 { get; set; }
        public string ProductServiceID_04 { get; set; }
        public string DatasetRequested_05 { get; set; }
        public string ProductServiceID_06 { get; set; }
        public string DatasetRequested_07 { get; set; }
        public string ProductServiceID_08 { get; set; }
        public string DatasetRequested_09 { get; set; }
        public string ProductServiceID_10 { get; set; }
        public string DatasetRequested_11 { get; set; }
        public string ProductServiceID_12 { get; set; }
        public string DatasetRequested_13 { get; set; }
        public string ProductServiceID_14 { get; set; }
        public string DatasetRequested_15 { get; set; }
        public string ProductServiceID_16 { get; set; }
        public string DatasetRequested_17 { get; set; }
    }
}
