//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nom1Done.Model
{
    using System;
    using System.Collections.Generic;

    public class RURD
    {
        public int Id { get; set; }
        public System.Guid TransactionID { get; set; }
        public string TransactionIdentifierCode { get; set; }
        public string TransactionControlNumber { get; set; }
        public string TransactionPurposeCode { get; set; }
        public string ReportTypeCode { get; set; }
        public string RequestID { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string EntityIdentifier { get; set; }
        public string IdentifierCodeQualifir { get; set; }
    }
}
