//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPRD.Model
{
    using System;
    using System.Collections.Generic;
    
    public class IncomingData
    {
        public string Id { get; set; }
        public string MessageId { get; set; }
        public string DataReceived { get; set; }
        public System.DateTime ReceivedAt { get; set; }
    }
}
