//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPRD.Model
{
    using System;
    using System.Collections.Generic;
    
    public class EmailQueue
    {
        public int Id { get; set; }
        public string ToUserID { get; set; }
        public string Subject { get; set; }
        public string Email { get; set; }
        public string Recipient { get; set; }
        public string CC { get; set; }
        public string Bcc { get; set; }
        public bool IsSent { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime SentDate { get; set; }
    }
}
