//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPRD.Model
{
    using System;
    using System.Collections.Generic;
    
    public class Inbox
    {
        public int Id { get; set; }
        public System.Guid MessageID { get; set; }
        public int DatasetID { get; set; }
        public int StatusID { get; set; }
        public string GISB { get; set; }
        public bool IsTest { get; set; }
        public bool IsRead { get; set; }
        public int PipelineID { get; set; }
        public int RecipientCompanyID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
