//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPRD.Model
{
    using System;
    using System.Collections.Generic;
    
    public class TaskMgrXml
    {
        public int Id { get; set; }
        public string TransactionId { get; set; }
        public string XmlData { get; set; }
        public int PipelineId { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<bool> IsProccessed { get; set; }
        public string EDIData { get; set; }
        public string EncEDIData { get; set; }
        public string SendUrl { get; set; }
    }
}
