//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralisedUprd.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobStackErrorLog
    {
        public long Id { get; set; }
        public long WorkflowId { get; set; }
        public System.Guid TranactionId { get; set; }
        public int StageId { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorType { get; set; }
    }
}
